name: CI - Build Extractor Docker

on:
  push:
    branches:
      - main
    paths:
      - 'extractor/**'
      - '.github/workflows/ci-build-extractor-docker.yml'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./extractor
          platforms: linux/amd64,linux/arm64
          file: ./extractor/Dockerfile
          push: true
          tags: ghcr.io/zchryr/vitalis/extractor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max